services:
  app_mysql:
    build: ./app 
    ports:
      - "${APP_PORT}:${APP_PORT}"
    depends_on:
      - mysql_db
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    env_file:
      - .env

  mysql_db:
    image: mysql:8.0.40-debian
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3306:3306"
    volumes:
      - datos_persistentes_BD-mysql:/var/lib/mysql
    env_file:
      - .env

volumes:
  datos_persistentes_BD-mysql:

